<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/02/28 16:05:20

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'symfony',
  'password' => '123456',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
